version: '3.9'

services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbit
    env_file:
      - .env
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBIT_DEFAULT_USER=${RABBIT_DEFAULT_USER}
      - RABBIT_DEFAULT_PASS=${RABBIT_DEFAULT_PASS}
    restart: always
  db:
    image: postgres:14.5
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: -p ${DB_PORT}
    depends_on:
      - rabbitmq
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    ports:
      - 5555:80
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  app:
    container_name: producer
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./srv_inventory:/app/srv_inventory
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq
    restart: always
    command: ["python", "main.py"]

volumes:
  postgres_data:
  pgadmin_data: